#!/usr/bin/env python

"""
Generates PDF names for name-table.h, replacing symbols invalid for .NET fields.
"""

import os, re
import pathlib

def replaceInvalidSymbol(m):
	return "PDF_MAKE_NAME(\""+m.group(1)+"\", _"+m.group(2)+")"

def main():
	os.chdir(os.path.join(os.path.dirname(__file__), ".."))

	name_table = open("mupdf/include/mupdf/pdf/name-table.h").read()
	name_table = re.sub(r"PDF_MAKE_NAME\(\"(.+?)\", (\d.*)\)", replaceInvalidSymbol, name_table)
	name_table = re.sub(r"/[/\*].*?\r?\n", "", name_table)

	target = open("MuPDFLib/!Include/name-table.h", "wt")
	target.write("// This file is automatically generated by sync_name_table.py from mupdf/include/mupdf/pdf/name-table.h\n")
	target.write(name_table)

	print("synced name-table.h")

if __name__ == "__main__":
	main()
